### PR TITLE
nginx-ingress-controller-image: handle rootless

### PR DESCRIPTION
**Pull request by flavio**
These changes are required to allow the image to be used by the upstream helm chart with pod security policy enabled.

This boils down to allow the execution of nginx as non-root user.

fixes bsc#1107700

Note well: that needs the `authbind` package to be available.

### CODE REVIEW

**Comment by mrostecki** [comment]
I guess that we need to create `authbind` package first? I don't see it on OBS.

**Comment by davidcassany** [comment]
@flavio note that this [SR](https://build.opensuse.org/request/show/639730) has been declined. We should not merge that until the authbind package is completely approved into Factory.

**Comment by flavio** [comment]
@davidcassany: thanks, I've filed a new [SR](https://build.opensuse.org/request/show/640050)

**Comment by flavio** [comment]
BTW, I have no idea about how to replace the `%%TAG%%` attribute. This should be changed to something like `0.15.1`.

**Comment by jordimassaguerpla** [comment]
> BTW, I have no idea about how to replace the `%%TAG%%` attribute. This should be changed to something like `0.15.1`.

TAG uses the version from the nginx-ingress-controller package. Since the package has been updated but it maintains the same version as before, 0.15.0, this tag will also be 0.15.0.

Ideally, we should add an extra tag that indicates the release number or change the version in the nginx-ingress-controller package.

**Comment by davidcassany** [comment]
@flavio I saw the [SR](https://build.opensuse.org/request/show/640050) got declined again. If that is OK for you can spend some time adding the rpmlint filters or checking what is actually that bad that causes a bunch of warnings. Just let me know if so.

On tagging side of things I just want to let you know that having this auto increasing tags on builds is actually possible. I am about to update all of them in order to get tags like `0.15.0` and `0.15.0-3.1` being `3.1` the release and `0.15.0` the main package version. I am just pending on a simple MR at SLE-15 that is currently going smooth.

Probably we could even add another tag with the major number of the version only, `0` in this case. This way would also have some stable tag (at least during each release cycle).

**Comment by davidcassany** [comment]
@drpaneas sorry I skimmed to fast the PR, the tags are already in place, thus I don't see any problem with the merge

**Pull request merged**
