### PR TITLE
WIP: Remove hardcoded values for container images

### PR DESCRIPTION
**Pull request by ereslibre**
**WIP**: not meant to be reviewed nor merged.

### CODE REVIEW

**Comment by ereslibre** [comment]
With this change I see:

```
$ docker load < /var/tmp/build-root/container-x86_64/usr/src/packages/KIWI-docker/kubic-velum.x86_64-4.0.0.docker.tar.xz
b1aaa534749f: Loading layer [==================================================>]  41.19MB/41.19MB                           
c59ee774e931: Loading layer [==================================================>]  56.89MB/56.89MB                                 
Loaded image: kubic/velum:0.0 
$ docker run --rm -it kubic/velum:0.0 bash
a2124e9c8790:/srv/velum # ls -la /bin/bundle 
lrwxrwxrwx 1 root root 55 Mar 20 11:54 /bin/bundle -> /srv/velum/vendor/bundle/ruby/2.5.0/bin/bundler.ruby2.5
a2124e9c8790:/srv/velum # bundle install
Traceback (most recent call last):
        2: from /bin/bundle:23:in `<main>'
        1: from /usr/lib64/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/usr/lib64/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundler (Gem::GemNotFoundException)
```

**Comment by sysrich** [comment]
Closed because superseded by merged changes

**Comment by ereslibre** [comment]
@sysrich The idea behind this change was to avoid hardcoded versions altogether so maintanability is easier. If you think this can help I can work on this again.

**Comment by sysrich** [comment]
Oh, hmm, you're right - Reopening

**Comment by mrostecki** [comment]
Closing - we are not doing anything with velum here anymore.

**Pull request closed without merging**
