### PR TITLE
Add the Docker image for cilium

### PR DESCRIPTION
**Pull request by nirmoy**

### CODE REVIEW

**Comment by nirmoy** [comment]
@davidcassany  right it was not required, removed now.

**Comment by davidcassany** [comment]
Well it is on the way https://build.opensuse.org/request/show/597367, just asked the very same thing to  @nirmoy

**Comment by sysrich** [comment]
Can we hold this back until it's passed legal and review-team review? 
I'm willing to take the gamble that we'll be able to make it work once it's passed those basic phases, but we've been burnt about skipping past those key steps quite a few times now and I really don't want to make Kubic any more broken than it already is.

**Comment by davidcassany** [comment]
sure, we can hold until is all green

**Comment by sysrich** [comment]
Okay removing my objection based on that condition - will try and keep an eye on the PR but I'll be happy if anyone else merges it once opensuse-review-team and legal-auto review has passed

Thanks!

**Comment by nirmoy** [comment]
https://build.opensuse.org/request/show/599876 -->  all the reviews are done for factory

**Comment by davidcassany** [comment]
Great, all green :+1: merging

**Pull request merged**
