### PR TITLE
Add pre checking script

### PR DESCRIPTION
**Pull request by davidcassany**
This PR adds the `pre_checking.sh` script that can be used to generate kubic and caasp description files from a `*kiwi.ini` description file template and also restructures and renames files to be used with the `pre_checking.sh` script.

### CODE REVIEW

**Comment by davidcassany** [comment]
[(5) Automate the workflow for CaaSP/Kubic images from the github repo](https://trello.com/c/zqouPBib/755-5-automate-the-workflow-for-caasp-kubic-images-from-the-github-repo)

**Comment by davidcassany** [comment]
@jordimassaguerpla I am not sure I understand your question. Are you referring into a case in which, for instance, a package that is listed (not that in most cases it is a single package) changes its name in Tumbleweed but not in whatever it is based CaaSP Head?

From one hand, I like to think this is unlikely to happen due to the small amount of involved packages and also because I believe we all try to keep package names stable. However, there is still the risk of that to happen as we can't foresee upcoming changes.

On the other hand I believe this is part of our duties trying to keep Kubic and CaaSP Head as close as possible. Note that it should only apply for CaaSP HEAD as this repository should also follow the branching approach in which there is a branch for each CaaSP release. Meaning that if there is a change in Tumbleweed like mentioned above we should care to make it also extensible to CaaSP HEAD or to whatever it is based CaaSP HEAD. The good thing of this approach is that the failure will happen automatically at the time there is a change of this nature and hopefully it will give us some time window to react and try to fix it without having to diverge Kubic and CaaSP code.

Said all that I agree that this is potential pitfall of this approach.

**Comment by jordimassaguerpla** [comment]
@davidcassany : I've been thinking about it.... I guess we could always do some replacement with the sed commands if needed, like "sed -s 'r/old_package/new_package/g'".

But that is a not a problem for now, so lgtm

**Comment by davidcassany** [comment]
@jordimassaguerpla yes, we could always do something similar to what is done for live cds, there is a common template description for all kde or gnome or whatever and then there is a list of specific packages for each that would be appended using the pre_checking.sh script.

**Pull request merged**
